// ----- HOW TO USE ------
//
// >>> Please, use ISO 639-1 Code to define language !!!!
//
// >>> Formatting in VS CODE>>>
// REGEX FOR SWITCHING TO EDITOR MODE:
// (".*?:)[\s]+?(".*,)
// replace to 
// $1\n        $2\n
// REGEX TO GO BACK TO COMPACT MODE:
// (".*?:)[\n\r\s]+?(".*,)[\n\r]
// replase to 
// $1 $2
// 
// >>> Use this to translate altogether >>>
// Your password was too weak, we generated a new strong one
// Please save it!
// First name must be longer than 2 characters, without special symbols or spaces
// Last name must be more than 2 characters, no special symbols or spaces
// The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces
// Phone number must be between 7 and 11 characters long, no special characters
// First name is required
// Can contain minimum 2 letters
// Can contain maximum 25 letters
// Last name is required
// Password is required
// Password must be at least 8 characters
// Password cannot exceed 12 characters
// E-mail address is required
// Insert a valid email address
// Phone is required
// ----------------------------

var pwd_msg_lang = {
    "en" : {
        "Your password was too weak, we generated a new strong one" : "Your password was too weak, we generated a new strong one",
        "Please save it!" : "Please save it!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "First name must be longer than 2 characters, without special symbols or spaces",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Last name must be more than 2 characters, no special symbols or spaces",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Phone number must be between 7 and 11 characters long, no special characters",
        "First name is required" : "First name is required",
        "Can contain minimum 2 letters" : "Can contain minimum 2 letters",
        "Can contain maximum 25 letters" : "Can contain maximum 25 letters",
        "Last name is required" : "Last name is required",
        "Password is required" : "Password is required",
        "Password must be at least 8 characters" : "Password must be at least 8 characters",
        "Password cannot exceed 12 characters" : "Password cannot exceed 12 characters",
        "E-mail address is required" : "E-mail address is required",
        "Insert a valid email address" : "Insert a valid email address",
        "Phone is required" : "Phone is required",
    },

    "hr" : {
        "Your password was too weak, we generated a new strong one" : "Vaša je lozinka bila preslaba, generirali smo novu jaku",
        "Please save it!" : "Molim vas, sačuvajte ga!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Ime mora biti duže od 2 znaka, bez posebnih simbola ili razmaka",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Prezime mora imati više od 2 znaka, bez posebnih simbola ili razmaka",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Lozinka mora imati između 6 i 12 znakova, uključujući slova (A-Z, a-z) i brojeve (0-9). Bez posebnih simbola (^@()_#*+/\"?!=.}}~` i razmaka",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefonski broj mora imati između 7 i 11 znakova, bez posebnih znakova",
        "First name is required" : "Ime je obavezno",
        "Can contain minimum 2 letters" : "Može sadržavati minimalno 2 slova",
        "Can contain maximum 25 letters" : "Može sadržavati najviše 25 slova",
        "Last name is required" : "Prezime je obavezno",
        "Password is required" : "Potrebna je lozinka",
        "Password must be at least 8 characters" : "Lozinka mora imati najmanje 8 znakova",
        "Password cannot exceed 12 characters" : "Lozinka ne smije biti duža od 12 znakova",
        "E-mail address is required" : "E-mail adresa je obavezna",
        "Insert a valid email address" : "Unesite valjanu adresu e-pošte",
        "Phone is required" : "Telefon je obavezan",
    },

    "cs" : {
        "Your password was too weak, we generated a new strong one" : "Vaše heslo bylo příliš slabé, vygenerovali jsme nové silné",
        "Please save it!" : "Prosím, uložte si to!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Jméno musí být delší než 2 znaky, bez speciálních symbolů a mezer",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Příjmení musí mít více než 2 znaky, žádné speciální symboly nebo mezery",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Heslo musí mít 6 až 12 znaků, včetně písmen (A-Z, a-z) a číslic (0-9). Bez speciálních symbolů (^@()_#*+/\"?!=.}}~` a mezer",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefonní číslo musí mít 7 až 11 znaků, žádné speciální znaky",
        "First name is required" : "Jméno je povinné",
        "Can contain minimum 2 letters" : "Může obsahovat minimálně 2 písmena",
        "Can contain maximum 25 letters" : "Může obsahovat maximálně 25 písmen",
        "Last name is required" : "Příjmení je povinné",
        "Password is required" : "Je vyžadováno heslo",
        "Password must be at least 8 characters" : "Heslo musí mít nejméně 8 znaků",
        "Password cannot exceed 12 characters" : "Heslo nesmí přesáhnout 12 znaků",
        "E-mail address is required" : "E-mailová adresa je povinná",
        "Insert a valid email address" : "Vložte platnou e-mailovou adresu",
        "Phone is required" : "Telefon je povinný",
    },

    "sk" : {
        "Your password was too weak, we generated a new strong one" : "Vaše heslo bolo príliš slabé, vygenerovali sme nové silné",
        "Please save it!" : "Uložte si to",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Krstné meno musí byť dlhšie ako 2 znaky, bez špeciálnych symbolov a medzier",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Priezvisko musí mať viac ako 2 znaky, žiadne špeciálne symboly ani medzery",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Heslo musí mať 6 až 12 znakov vrátane písmen (A-Z, a-z) a číslic (0-9). Bez špeciálnych symbolov (^@()_#*+/\"?!=.}}~` a medzier",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefónne číslo musí mať 7 až 11 znakov, žiadne špeciálne znaky",
        "First name is required" : "Vyžaduje sa krstné meno",
        "Can contain minimum 2 letters" : "Môže obsahovať minimálne 2 písmená",
        "Can contain maximum 25 letters" : "Môže obsahovať maximálne 25 písmen",
        "Last name is required" : "Vyžaduje sa priezvisko",
        "Password is required" : "Vyžaduje sa heslo",
        "Password must be at least 8 characters" : "Heslo musí mať aspoň 8 znakov",
        "Password cannot exceed 12 characters" : "Heslo nesmie presiahnuť 12 znakov",
        "E-mail address is required" : "Vyžaduje sa e-mailová adresa",
        "Insert a valid email address" : "Zadajte platnú e-mailovú adresu",
        "Phone is required" : "Vyžaduje sa telefón",
    },

    "it" : {
        "Your password was too weak, we generated a new strong one" : "La tua password era troppo debole, ne abbiamo generata una nuova forte",
        "Please save it!" : "Per favore salvalo!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Il nome deve essere più lungo di 2 caratteri, senza simboli o spazi speciali",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Il cognome deve contenere più di 2 caratteri, nessun simbolo o spazio speciale",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "La password deve contenere da 6 a 12 caratteri, comprese lettere (A-Z, a-z) e numeri (0-9). Senza simboli speciali (^@()_#*+/\"?!=.}}~` e spazi",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Il numero di telefono deve contenere da 7 a 11 caratteri, nessun carattere speciale",
        "First name is required" : "Il nome è obbligatorio",
        "Can contain minimum 2 letters" : "Può contenere minimo 2 lettere",
        "Can contain maximum 25 letters" : "Può contenere un massimo di 25 lettere",
        "Last name is required" : "Il cognome è obbligatorio",
        "Password is required" : "E 'richiesta la password",
        "Password must be at least 8 characters" : "La password deve essere di almeno 8 caratteri",
        "Password cannot exceed 12 characters" : "La password non può superare i 12 caratteri",
        "E-mail address is required" : "L'indirizzo e-mail è obbligatorio",
        "Insert a valid email address" : "Inserisci un indirizzo email valido",
        "Phone is required" : "È necessario il telefono",
    },

    "el" : {
        "Your password was too weak, we generated a new strong one" : "Ο κωδικός πρόσβασής σας ήταν πολύ αδύναμος, δημιουργήσαμε έναν νέο ισχυρό",
        "Please save it!" : "Παρακαλώ αποθηκεύστε το!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Το όνομα πρέπει να είναι μεγαλύτερο από 2 χαρακτήρες, χωρίς ειδικά σύμβολα ή κενά",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Το επώνυμο πρέπει να αποτελείται από περισσότερους από 2 χαρακτήρες, χωρίς ειδικά σύμβολα ή κενά",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Ο κωδικός πρόσβασης πρέπει να αποτελείται από 6 έως 12 χαρακτήρες, συμπεριλαμβανομένων των γραμμάτων (A-Z, a-z) και των αριθμών (0-9). Χωρίς ειδικά σύμβολα (^@()_#*+/\"?!=.}}~` και κενά",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Ο αριθμός τηλεφώνου πρέπει να αποτελείται από 7 έως 11 χαρακτήρες, χωρίς ειδικούς χαρακτήρες",
        "First name is required" : "Το όνομα είναι υποχρεωτικό",
        "Can contain minimum 2 letters" : "Μπορεί να περιέχει τουλάχιστον 2 γράμματα",
        "Can contain maximum 25 letters" : "Μπορεί να περιέχει έως 25 γράμματα",
        "Last name is required" : "Το επώνυμο είναι υποχρεωτικό",
        "Password is required" : "Απαιτείται κωδικός",
        "Password must be at least 8 characters" : "Ο κωδικός πρέπει να έχει τουλάχιστον 8 χαρακτήρες",
        "Password cannot exceed 12 characters" : "Ο κωδικός πρόσβασης δεν μπορεί να υπερβαίνει τους 12 χαρακτήρες",
        "E-mail address is required" : "Απαιτείται διεύθυνση e-mail",
        "Insert a valid email address" : "Εισαγάγετε μια έγκυρη διεύθυνση email",
        "Phone is required" : "Απαιτείται τηλέφωνο",
    },

    "fr" : {
        "Your password was too weak, we generated a new strong one" : "Votre mot de passe était trop faible, nous en avons généré un nouveau fort",
        "Please save it!" : "S'il vous plaît, enregistrez-le !",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Le prénom doit comporter plus de 2 caractères, sans symboles spéciaux ni espaces",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Le nom de famille doit comporter plus de 2 caractères, pas de symboles spéciaux ni d'espaces",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Le mot de passe doit comporter entre 6 et 12 caractères, y compris des lettres (A-Z, a-z) et des chiffres (0-9). Sans symboles spéciaux (^@()_#*+/\"?!=.}}~` et espaces",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Le numéro de téléphone doit comporter entre 7 et 11 caractères, pas de caractères spéciaux",
        "First name is required" : "Le prénom est requis",
        "Can contain minimum 2 letters" : "Peut contenir au moins 2 lettres",
        "Can contain maximum 25 letters" : "Peut contenir 25 lettres maximum",
        "Last name is required" : "Le nom de famille est requis",
        "Password is required" : "Mot de passe requis",
        "Password must be at least 8 characters" : "Mot de passe doit être d'au moins 8 caractères",
        "Password cannot exceed 12 characters" : "Le mot de passe ne peut pas dépasser 12 caractères",
        "E-mail address is required" : "Adresse e-mail est nécessaire",
        "Insert a valid email address" : "Insérez une adresse e-mail valide",
        "Phone is required" : "Le téléphone est requis",
    },

    "sl" : {
        "Your password was too weak, we generated a new strong one" : "Vaše geslo je bilo prešibko, ustvarili smo novo močno",
        "Please save it!" : "Prosim, shranite!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Ime mora biti daljše od 2 znakov, brez posebnih znakov ali presledkov",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Priimek mora vsebovati več kot 2 znaka, brez posebnih znakov ali presledkov",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Geslo mora vsebovati med 6 in 12 znaki, vključno s črkami (A-Z, a-z) in številkami (0-9). Brez posebnih simbolov (^@()_#*+/\"?!=.}}~` in presledkov",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefonska številka mora biti dolga od 7 do 11 znakov, brez posebnih znakov",
        "First name is required" : "Ime je obvezno",
        "Can contain minimum 2 letters" : "Lahko vsebuje najmanj 2 črki",
        "Can contain maximum 25 letters" : "Lahko vsebuje največ 25 črk",
        "Last name is required" : "Priimek je obvezen",
        "Password is required" : "Zahtevano je geslo",
        "Password must be at least 8 characters" : "Geslo mora imeti vsaj 8 znakov",
        "Password cannot exceed 12 characters" : "Geslo ne sme presegati 12 znakov",
        "E-mail address is required" : "E-mail naslov je obvezen",
        "Insert a valid email address" : "Vnesite veljaven e-mail naslov",
        "Phone is required" : "Potreben je telefon",
    },
    "hu" : {
        "Your password was too weak, we generated a new strong one" : "A jelszava túl gyenge, ezért új, erős jelszót generáltunk",
        "Please save it!" : "Kérem mentse el!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "A keresztnévnek 2 karakternél hosszabbnak kell lennie, speciális szimbólumok és szóközök nélkül",
        "Last name must be more than 2 characters, no special symbols or spaces" : "A vezetéknévnek több mint 2 karakterből kell állnia, speciális szimbólumok vagy szóközök nélkül",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "A jelszónak 6 és 12 karakter között kell lennie, beleértve a betűket (A-Z, a-z) és a számokat (0-9). Különleges szimbólumok (^@()_#*+/\"?!=.}}~` és szóközök nélkül",
        "Phone number must be between 7 and 11 characters long, no special characters" : "A telefonszámnak 7 és 11 karakter között kell lennie, speciális karakterek nem lehetnek",
        "First name is required" : "A keresztnév megadása kötelező",
        "Can contain minimum 2 letters" : "Legalább 2 betűt tartalmazhat",
        "Can contain maximum 25 letters" : "Maximum 25 betűt tartalmazhat",
        "Last name is required" : "A vezetéknév megadása kötelező",
        "Password is required" : "Jelszó szükséges",
        "Password must be at least 8 characters" : "A jelszónak legalább 8 karakterből kell állnia",
        "Password cannot exceed 12 characters" : "A jelszó nem haladhatja meg a 12 karaktert",
        "E-mail address is required" : "E-mail cím megadása kötelező",
        "Insert a valid email address" : "Adjon meg egy érvényes e-mail címet",
        "Phone is required" : "Telefon szükséges",
    },
    "pt" : {
        "Your password was too weak, we generated a new strong one" : "Sua senha era muito fraca, geramos uma nova senha forte",
        "Please save it!" : "Por favor, salve!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "O nome deve ter mais de 2 caracteres, sem símbolos ou espaços especiais",
        "Last name must be more than 2 characters, no special symbols or spaces" : "O sobrenome deve ter mais de 2 caracteres, sem símbolos ou espaços especiais",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "A senha deve ter entre 6 e 12 caracteres, incluindo letras (A-Z, a-z) e números (0-9). Sem símbolos especiais (^@()_#*+/\"?!=.}}~` e espaços",
        "Phone number must be between 7 and 11 characters long, no special characters" : "O número de telefone deve ter entre 7 e 11 caracteres, sem caracteres especiais",
        "First name is required" : "O primeiro nome é necessário",
        "Can contain minimum 2 letters" : "Pode conter no mínimo 2 letras",
        "Can contain maximum 25 letters" : "Pode conter no máximo 25 letras",
        "Last name is required" : "O sobrenome é obrigatório",
        "Password is required" : "Senha requerida",
        "Password must be at least 8 characters" : "A senha deve conter pelo menos 8 caracteres",
        "Password cannot exceed 12 characters" : "A senha não pode exceder 12 caracteres",
        "E-mail address is required" : "É necessário um endereço de e-mail",
        "Insert a valid email address" : "Insira um endereço de e-mail válido",
        "Phone is required" : "O telefone é obrigatório",
    },
    "es" : {
        "Your password was too weak, we generated a new strong one" : "Su contraseña era demasiado débil, generamos una nueva fuerte",
        "Please save it!" : "¡Por favor, guárdalo!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "El nombre debe tener más de 2 caracteres, sin símbolos ni espacios especiales",
        "Last name must be more than 2 characters, no special symbols or spaces" : "El apellido debe tener más de 2 caracteres, sin símbolos ni espacios especiales",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "La contraseña debe tener entre 6 y 12 caracteres, incluidas letras (A-Z, a-z) y números (0-9). Sin símbolos especiales (^@()_#*+/\"?!=.}}~` y espacios",
        "Phone number must be between 7 and 11 characters long, no special characters" : "El número de teléfono debe tener entre 7 y 11 caracteres, sin caracteres especiales",
        "First name is required" : "Se requiere el primer nombre",
        "Can contain minimum 2 letters" : "Puede contener mínimo 2 letras",
        "Can contain maximum 25 letters" : "Puede contener un máximo de 25 letras",
        "Last name is required" : "Se requiere apellido",
        "Password is required" : "Se requiere contraseña",
        "Password must be at least 8 characters" : "La contraseña debe tener al menos 8 caracteres",
        "Password cannot exceed 12 characters" : "La contraseña no puede exceder los 12 caracteres",
        "E-mail address is required" : "Se requiere Dirección de correo electrónico",
        "Insert a valid email address" : "Inserte una dirección de correo electrónico válida",
        "Phone is required" : "Se requiere teléfono",
    },

    "ro" : {
        "Your password was too weak, we generated a new strong one" : "Parola dvs. a fost prea slabă, am generat una nouă puternică",
        "Please save it!" : "Te rog, salvează-l!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Prenumele trebuie să aibă mai mult de 2 caractere, fără simboluri sau spații speciale",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Numele de familie trebuie să aibă mai mult de 2 caractere, fără simboluri sau spații speciale",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Parola trebuie să aibă între 6 și 12 caractere, inclusiv litere (A-Z, a-z) și cifre (0-9). Fără simboluri speciale (^@()_#*+/\"?!=.}}~` și spații",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Numărul de telefon trebuie să aibă între 7 și 11 caractere, fără caractere speciale",
        "First name is required" : "Prenumele este obligatoriu",
        "Can contain minimum 2 letters" : "Poate conține minim 2 litere",
        "Can contain maximum 25 letters" : "Poate conține maximum 25 de litere",
        "Last name is required" : "Numele de familie este obligatoriu",
        "Password is required" : "Parola este necesara",
        "Password must be at least 8 characters" : "Parola trebuie să fie de cel puțin 8 caractere",
        "Password cannot exceed 12 characters" : "Parola nu poate depăși 12 caractere",
        "E-mail address is required" : "Este necesară adresa de e-mail",
        "Insert a valid email address" : "Introduceți o adresă de e-mail validă",
        "Phone is required" : "Este necesar telefonul",
    },

    "de" : {
        "Your password was too weak, we generated a new strong one" : "Ihr Passwort war zu schwach, wir haben ein neues starkes generiert",
        "Please save it!" : "Bitte speichern!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Der Vorname muss länger als 2 Zeichen sein, ohne Sonderzeichen oder Leerzeichen",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Nachname muss mehr als 2 Zeichen lang sein, keine Sonderzeichen oder Leerzeichen",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Das Passwort muss zwischen 6 und 12 Zeichen lang sein, einschließlich Buchstaben (A-Z, a-z) und Zahlen (0-9). Ohne Sonderzeichen (^@()_#*+/\"?!=.}}~` und Leerzeichen",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefonnummer muss zwischen 7 und 11 Zeichen lang sein, keine Sonderzeichen",
        "First name is required" : "Vorname ist erforderlich",
        "Can contain minimum 2 letters" : "Kann mindestens 2 Buchstaben enthalten",
        "Can contain maximum 25 letters" : "Kann maximal 25 Buchstaben enthalten",
        "Last name is required" : "Nachname ist erforderlich",
        "Password is required" : "Passwort wird benötigt",
        "Password must be at least 8 characters" : "Das Passwort muss mindestens 8 Zeichen lang sein",
        "Password cannot exceed 12 characters" : "Das Passwort darf 12 Zeichen nicht überschreiten",
        "E-mail address is required" : "E-Mailadresse wird benötigt",
        "Insert a valid email address" : "Geben Sie eine gültige E-Mail-Adresse ein",
        "Phone is required" : "Telefon ist erforderlich",
    },

    "tr" : {
        "Your password was too weak, we generated a new strong one" : "Şifreniz çok zayıftı, yeni bir güçlü şifre oluşturduk",
        "Please save it!" : "Lütfen kaydedin!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Ad, özel semboller veya boşluklar olmadan 2 karakterden uzun olmalıdır",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Soyadı 2 karakterden uzun olmalı, özel sembol veya boşluk olmamalıdır",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Şifre, harfler (A-Z, a-z) ve sayılar (0-9) dahil olmak üzere 6 ila 12 karakter arasında olmalıdır. Özel semboller (^@()_#*+/\"?!=.}}~` ve boşluklar olmadan",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefon numarası 7 ila 11 karakter uzunluğunda olmalı, özel karakter olmamalıdır",
        "First name is required" : "Ad gerekli",
        "Can contain minimum 2 letters" : "En az 2 harf içerebilir",
        "Can contain maximum 25 letters" : "Maksimum 25 harf içerebilir",
        "Last name is required" : "Soyadı gerekli",
        "Password is required" : "Şifre gereklidir",
        "Password must be at least 8 characters" : "Şifre en az 8 karakter olmalıdır",
        "Password cannot exceed 12 characters" : "Şifre 12 karakteri aşamaz",
        "E-mail address is required" : "E-posta adresi gerekli",
        "Insert a valid email address" : "Geçerli bir e-posta adresi girin",
        "Phone is required" : "Telefon gerekli",
    },
    "nl" : {
        "Your password was too weak, we generated a new strong one" : "Je wachtwoord was te zwak, we hebben een nieuw sterk wachtwoord gegenereerd",
        "Please save it!" : "Bewaar het alsjeblieft!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Voornaam moet langer zijn dan 2 tekens, zonder speciale symbolen of spaties",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Achternaam moet meer dan 2 tekens bevatten, geen speciale symbolen of spaties",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Het wachtwoord moet tussen 6 en 12 tekens lang zijn, inclusief letters (A-Z, a-z) en cijfers (0-9). Zonder speciale symbolen (^@()_#*+/\"?!=.}}~` en spaties",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefoonnummer moet tussen 7 en 11 tekens lang zijn, geen speciale tekens",
        "First name is required" : "Voornaam is verplicht",
        "Can contain minimum 2 letters" : "Mag minimaal 2 letters bevatten",
        "Can contain maximum 25 letters" : "Mag maximaal 25 letters bevatten",
        "Last name is required" : "Achternaam is verplicht",
        "Password is required" : "Een wachtwoord is verplicht",
        "Password must be at least 8 characters" : "Wachtwoord moet minimaal 8 tekens lang zijn",
        "Password cannot exceed 12 characters" : "Wachtwoord mag niet langer zijn dan 12 tekens",
        "E-mail address is required" : "E-mailadres is verplicht",
        "Insert a valid email address" : "Voer een geldig e-mailadres in",
        "Phone is required" : "Telefoon is vereist",
    },

    "pl" : {
        "Your password was too weak, we generated a new strong one" : "Twoje hasło było zbyt słabe, wygenerowaliśmy nowe silne hasło",
        "Please save it!" : "Proszę to zapisać!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Imię musi być dłuższe niż 2 znaki, bez symboli specjalnych i spacji",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Nazwisko musi zawierać więcej niż 2 znaki, bez symboli specjalnych i spacji",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Hasło musi zawierać od 6 do 12 znaków, w tym litery (A-Z, a-z) i cyfry (0-9). Bez symboli specjalnych (^@()_#*+/?!=.}}~` i spacji",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Numer telefonu musi mieć długość od 7 do 11 znaków, bez znaków specjalnych",
        "First name is required" : "Imię jest wymagane",
        "Can contain minimum 2 letters" : "Może zawierać minimum 2 litery",
        "Can contain maximum 25 letters" : "Może zawierać maksymalnie 25 liter",
        "Last name is required" : "Nazwisko jest wymagane",
        "Password is required" : "Hasło jest wymagane",
        "Password must be at least 8 characters" : "Hasło musi składać się z co najmniej 8 znaków",
        "Password cannot exceed 12 characters" : "Hasło nie może przekraczać 12 znaków",
        "E-mail address is required" : "Wymagany jest adres e-mail",
        "Insert a valid email address" : "Wprowadź prawidłowy adres e-mail",
        "Phone is required" : "Telefon jest wymagany",
    },
    "zh" : {
        "Your password was too weak, we generated a new strong one" : "您的密碼太弱，我們生成了一個新的強密碼",
        "Please save it!" : "請保存！",
        "First name must be longer than 2 characters, without special symbols or spaces" : "名字必須超過 2 個字符，不能有特殊符號或空格",
        "Last name must be more than 2 characters, no special symbols or spaces" : "姓氏必須超過 2 個字符，不能有特殊符號或空格",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "密碼必須介於 6 到 12 個字符之間，包括字母（A-Z、a-z）和數字 (0-9)。 沒有特殊符號 (^@()_#*+/\"?!=.}}~` 和空格",
        //old "Phone number must be between 7 and 11 characters long, no special characters" : "電話號碼長度必須在 7 到 11 個字符之間，不能有特殊字符",
        "Phone number must be between 7 and 11 characters long, no special characters" : "電話號碼長度必須在 7 到 11 個數字之間，不能有特殊字符",
        //old "First name is required" : "名字是必填項",
        "First name is required" : "名字是必填項目",
        "Can contain minimum 2 letters" : "可以包含至少 2 個字母",
        "Can contain maximum 25 letters" : "最多可包含 25 個字母",
        //old "Last name is required" : "姓氏為必填項",
        "Last name is required" : "姓氏為必填項目",
        "Password is required" : "密碼是必需的",
        "Password must be at least 8 characters" : "密碼必須至少8個字符",
        "Password cannot exceed 12 characters" : "密碼不能超過 12 個字符",
        //old "E-mail address is required" : "電子郵件地址為必填項",
        "E-mail address is required" : "電子郵件地址為必填項目",
        //old "Insert a valid email address" : "插入有效的電子郵件地址",
        "Insert a valid email address" : "請填寫有效的電子郵件",
        //old "Phone is required" : "電話是必需的",
        "Phone is required" : "電話是必填項目",
    },

    "ar" : {
        "Your password was too weak, we generated a new strong one" : "كلمة مرورك كانت ضعيفة للغاية ، أنشأنا كلمة مرور جديدة قوية",
        "Please save it!" : "يرجى حفظه!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "يجب أن يكون الاسم الأول أطول من حرفين ، بدون رموز خاصة أو مسافات",
        "Last name must be more than 2 characters, no special symbols or spaces" : "يجب أن يكون اسم العائلة أكثر من حرفين ، بدون رموز خاصة أو مسافات",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "يجب أن تتكون كلمة المرور من 6 إلى 12 حرفًا ، بما في ذلك الأحرف (A-Z ، a-z) والأرقام (0-9). بدون رموز خاصة (^@()_#*+/\"?!=.}}~` ومسافات",
        "Phone number must be between 7 and 11 characters long, no special characters" : "يجب أن يتراوح طول رقم الهاتف بين 7 و 11 حرفًا ، بدون أحرف خاصة",
        "First name is required" : "الإسم الأول مطلوب",
        "Can contain minimum 2 letters" : "يمكن أن تحتوي على حرفين على الأقل",
        "Can contain maximum 25 letters" : "يمكن أن تحتوي على 25 حرفًا كحد أقصى",
        "Last name is required" : "إسم العائلة مطلوب",
        "Password is required" : "كلمة المرور مطلوبة",
        "Password must be at least 8 characters" : "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
        "Password cannot exceed 12 characters" : "لا يمكن أن تتجاوز كلمة المرور 12 حرفًا",
        "E-mail address is required" : "مطلوب عنوان البريد الإلكتروني",
        "Insert a valid email address" : "أدخل عنوان بريد إلكتروني صالح",
        "Phone is required" : "الهاتف مطلوب",
    },

    "hi" : {
        "Your password was too weak, we generated a new strong one" : "आपका पासवर्ड बहुत कमज़ोर था, हमने एक नया मज़बूत जनरेट किया है",
        "Please save it!" : "कृपया इसे बचा लें!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "पहला नाम 2 वर्णों से अधिक लंबा होना चाहिए, विशेष प्रतीकों या रिक्त स्थान के बिना",
        "Last name must be more than 2 characters, no special symbols or spaces" : "अंतिम नाम 2 वर्णों से अधिक होना चाहिए, कोई विशेष प्रतीक या रिक्त स्थान नहीं होना चाहिए",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "पासवर्ड 6 और 12 वर्णों के बीच होना चाहिए, जिसमें अक्षर (A-Z, a-z) और अंक (0-9) शामिल हैं। विशेष प्रतीकों के बिना (^@()_#*+/\"?!=.}}~` और रिक्त स्थान",
        "Phone number must be between 7 and 11 characters long, no special characters" : "फ़ोन नंबर 7 से 11 वर्णों के बीच होना चाहिए, कोई विशेष वर्ण नहीं होना चाहिए",
        "First name is required" : "पहला नाम आवश्यक है",
        "Can contain minimum 2 letters" : "कम से कम 2 अक्षर हो सकते हैं",
        "Can contain maximum 25 letters" : "अधिकतम 25 अक्षर हो सकते हैं",
        "Last name is required" : "अंतिम नाम आवश्यक है",
        "Password is required" : "पासवर्ड की आवश्यकता है",
        "Password must be at least 8 characters" : "पासवर्ड कम से कम 8 वर्णों का होना चाहिए",
        "Password cannot exceed 12 characters" : "पासवर्ड 12 वर्णों से अधिक नहीं हो सकता",
        "E-mail address is required" : "ईमेल पते की ज़रुरत है",
        "Insert a valid email address" : "एक वैध ईमेल पता डालें",
        "Phone is required" : "फ़ोन आवश्यक है",
    },

    "sq" : {
        "Your password was too weak, we generated a new strong one" : "Fjalëkalimi yt ishte shumë i dobët, ne krijuam një të ri të fortë",
        "Please save it!" : "Ju lutemi ruajeni!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Emri duhet të jetë më i gjatë se 2 karaktere, pa simbole ose hapësira të veçanta",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Mbiemri duhet të jetë më shumë se 2 karaktere, pa simbole apo hapësira të veçanta",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Fjalëkalimi duhet të jetë nga 6 deri në 12 karaktere, duke përfshirë shkronjat (A-Z, a-z) dhe numrat (0-9). Pa simbole të veçanta (^@()_#*+/\"?!=.}}~` dhe hapësira",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Numri i telefonit duhet të jetë nga 7 deri në 11 karaktere, pa karaktere të veçanta",
        "First name is required" : "Kërkohet emri",
        "Can contain minimum 2 letters" : "Mund të përmbajë të paktën 2 shkronja",
        "Can contain maximum 25 letters" : "Mund të përmbajë maksimumi 25 shkronja",
        "Last name is required" : "Mbiemri kërkohet",
        "Password is required" : "Kërkohet fjalëkalimi",
        "Password must be at least 8 characters" : "Fjalëkalimi duhet të jetë së paku 8 karaktere",
        "Password cannot exceed 12 characters" : "Fjalëkalimi nuk mund të kalojë 12 karaktere",
        "E-mail address is required" : "Kërkohet adresa e postës elektronike",
        "Insert a valid email address" : "Fut një adresë të vlefshme emaili",
        "Phone is required" : "Kërkohet telefon",
    },

    "no" : {
        "Your password was too weak, we generated a new strong one" : "Passordet ditt var for svakt, vi genererte et nytt sterkt passord.",
        "Please save it!" : "Vennligst lagre det!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Fornavnet må være lengre enn 2 tegn, uten spesielle symboler eller mellomrom.",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Etternavn må være mer enn 2 tegn, ingen spesielle symboler eller mellomrom.",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Passordet må være på mellom 6 og 12 tegn, inkludert bokstaver (A-Z, a-z) og tall (0-9). Uten spesialtegn (^@()_#*+/\"?!=.}}~` og mellomrom.",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefonnummeret må være mellom 7 og 11 tegn langt, ingen spesialtegn.",
        "First name is required" : "Fornavn er påkrevd",
        "Can contain minimum 2 letters" : "Kan inneholde minst 2 bokstaver",
        "Can contain maximum 25 letters" : "Kan inneholde maksimalt 25 bokstaver",
        "Last name is required" : "Etternavn er påkrevd",
        "Password is required" : "Passord er påkrevd",
        "Password must be at least 8 characters" : "Passordet må være på minst 8 tegn",
        "Password cannot exceed 12 characters" : "Passordet kan ikke overstige 12 tegn",
        "E-mail address is required" : "E-postadresse er påkrevd",
        "Insert a valid email address" : "Sett inn en gyldig e-postadresse",
        "Phone is required" : "Telefon er påkrevd",
    },

    "sv" : {
        "Your password was too weak, we generated a new strong one" : "Ditt lösenord var för svagt, vi skapade ett nytt starkt",
        "Please save it!" : "Spara den!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Förnamn måste vara längre än 2 tecken, utan speciella symboler eller mellanslag",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Efternamnet måste bestå av fler än 2 tecken, inga speciella symboler eller mellanslag",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Lösenordet måste vara mellan 6 och 12 tecken, inklusive bokstäver (A-Z, a-z) och siffror (0-9). Utan speciella symboler (^@()_#*+/\"?!=.}}~` och mellanslag",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefonnumret måste vara mellan 7 och 11 tecken långt, inga specialtecken",
        "First name is required" : "Förnamn krävs",
        "Can contain minimum 2 letters" : "Kan innehålla minst 2 bokstäver",
        "Can contain maximum 25 letters" : "Kan innehålla max 25 bokstäver",
        "Last name is required" : "Efternamn krävs",
        "Password is required" : "lösenord krävs",
        "Password must be at least 8 characters" : "Lösenordet måste bestå av minst 8 tecken",
        "Password cannot exceed 12 characters" : "Lösenordet får inte överstiga 12 tecken",
        "E-mail address is required" : "E-postadress krävs",
        "Insert a valid email address" : "Ange en giltig e-postadress",
        "Phone is required" : "Telefon krävs",
    },

    "bg" : {
        "Your password was too weak, we generated a new strong one" : "Вашата парола беше твърде слаба, ние генерирахме нова силна",
        "Please save it!" : "Моля, запазете го!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Името трябва да е по-дълго от 2 знака, без специални символи или интервали",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Фамилията трябва да е повече от 2 знака, без специални символи или интервали",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Паролата трябва да е между 6 и 12 знака, включително букви (A-Z, a-z) и цифри (0-9). Без специални символи (^@()_#*+/\"?!=.}}~` и интервали",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Телефонният номер трябва да е между 7 и 11 знака, без специални знаци",
        "First name is required" : "Първото име е задължително",
        "Can contain minimum 2 letters" : "Може да съдържа минимум 2 букви",
        "Can contain maximum 25 letters" : "Може да съдържа максимум 25 букви",
        "Last name is required" : "Фамилията е задължителна",
        "Password is required" : "изисква се парола",
        "Password must be at least 8 characters" : "Паролата трябва да е поне 8 знака",
        "Password cannot exceed 12 characters" : "Паролата не може да надвишава 12 знака",
        "E-mail address is required" : "Изисква се имейл адрес",
        "Insert a valid email address" : "Въведете валиден имейл адрес",
        "Phone is required" : "Изисква се телефон",
    },

    "da" : {
        "Your password was too weak, we generated a new strong one" : "Din adgangskode var for svag, vi genererede en ny, stærk",
        "Please save it!" : "Gem det venligst!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Fornavn skal være længere end 2 tegn uden specielle symboler eller mellemrum",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Efternavn skal være på mere end 2 tegn, ingen specielle symboler eller mellemrum",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Adgangskoden skal være mellem 6 og 12 tegn, inklusive bogstaver (A-Z, a-z) og tal (0-9). Uden specielle symboler (^@()_#*+/\"?!=.}}~` og mellemrum",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefonnummeret skal være mellem 7 og 11 tegn langt, ingen specialtegn",
        "First name is required" : "Fornavn er påkrævet",
        "Can contain minimum 2 letters" : "Kan indeholde minimum 2 bogstaver",
        "Can contain maximum 25 letters" : "Kan maksimalt indeholde 25 bogstaver",
        "Last name is required" : "Efternavn er påkrævet",
        "Password is required" : "adgangskode er påkrævet",
        "Password must be at least 8 characters" : "Adgangskoden skal være på mindst 8 tegn",
        "Password cannot exceed 12 characters" : "Adgangskoden må ikke overstige 12 tegn",
        "E-mail address is required" : "E-mail-adresse er påkrævet",
        "Insert a valid email address" : "Indsæt en gyldig e-mailadresse",
        "Phone is required" : "Telefon er påkrævet",
    },

    "fi" : {
        "Your password was too weak, we generated a new strong one" : "Salasanasi oli liian heikko, loimme uuden vahvan",
        "Please save it!" : "Ole hyvä ja tallenna se!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Etunimen tulee olla pidempi kuin 2 merkkiä ilman erikoismerkkejä tai välilyöntejä",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Sukunimessä on yli 2 merkkiä, ei erikoisia tai välilyöntejä",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Salasanassa on oltava 6–12 merkkiä, mukaan lukien kirjaimet (A–Z, a–z) ja numerot (0–9). Ilman erikoismerkkejä (^@()_#*+/\"?!=.}}~` ja välilyöntejä",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Puhelinnumeron tulee olla 7–11 merkkiä pitkä, ei erikoismerkkejä",
        "First name is required" : "Etunimi vaaditaan",
        "Can contain minimum 2 letters" : "Saa sisältää vähintään 2 kirjainta",
        "Can contain maximum 25 letters" : "Saa sisältää enintään 25 kirjainta",
        "Last name is required" : "Sukunimi vaaditaan",
        "Password is required" : "salasana tarvitaan",
        "Password must be at least 8 characters" : "Salasanassa on oltava vähintään 8 merkkiä",
        "Password cannot exceed 12 characters" : "Salasana ei saa ylittää 12 merkkiä",
        "E-mail address is required" : "Sähköpostiosoite vaaditaan",
        "Insert a valid email address" : "Lisää kelvollinen sähköpostiosoite",
        "Phone is required" : "Puhelin vaaditaan",
    },

    "id" : {
        "Your password was too weak, we generated a new strong one" : "Kata sandi Anda terlalu lemah, kami membuat kata sandi baru yang kuat",
        "Please save it!" : "Tolong simpan!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Nama depan harus lebih dari 2 karakter, tanpa simbol atau spasi khusus",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Nama belakang harus lebih dari 2 karakter, tidak boleh ada simbol atau spasi khusus",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Kata sandi harus antara 6 dan 12 karakter, termasuk huruf (A-Z, a-z) dan angka (0-9). Tanpa simbol khusus (^@()_#*+/\"?!=.}}~` dan spasi",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Nomor telepon harus terdiri dari 7 hingga 11 karakter, tanpa karakter khusus",
        "First name is required" : "Nama depan wajib diisi",
        "Can contain minimum 2 letters" : "Boleh berisi minimal 2 huruf",
        "Can contain maximum 25 letters" : "Dapat memuat maksimal 25 huruf",
        "Last name is required" : "Nama belakang wajib diisi",
        "Password is required" : "katakunci dibutuhkan",
        "Password must be at least 8 characters" : "Kata sandi minimal harus 8 karakter",
        "Password cannot exceed 12 characters" : "Kata sandi tidak boleh melebihi 12 karakter",
        "E-mail address is required" : "Alamat email diperlukan",
        "Insert a valid email address" : "Masukkan alamat email yang valid",
        "Phone is required" : "Telepon diperlukan",
    },

    "ms" : {
        "Your password was too weak, we generated a new strong one" : "Kata laluan anda terlalu lemah, kami menghasilkan kata laluan baharu yang kuat",
        "Please save it!" : "Tolong simpan!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Nama pertama mestilah lebih panjang daripada 2 aksara, tanpa simbol atau ruang khas",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Nama keluarga mestilah lebih daripada 2 aksara, tiada simbol atau ruang khas",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Kata laluan mestilah antara 6 dan 12 aksara, termasuk huruf (A-Z, a-z) dan nombor (0-9). Tanpa simbol khas (^@()_#*+/\"?!=.}}~` dan ruang",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Nombor telefon mestilah antara 7 dan 11 aksara panjang, tiada aksara khas",
        "First name is required" : "Nama pertama diperlukan",
        "Can contain minimum 2 letters" : "Boleh mengandungi minimum 2 huruf",
        "Can contain maximum 25 letters" : "Boleh mengandungi maksimum 25 huruf",
        "Last name is required" : "Nama keluarga diperlukan",
        "Password is required" : "kata laluan diperlukan",
        "Password must be at least 8 characters" : "Kata laluan mestilah sekurang-kurangnya 8 aksara",
        "Password cannot exceed 12 characters" : "Kata laluan tidak boleh melebihi 12 aksara",
        "E-mail address is required" : "Alamat e-mel diperlukan",
        "Insert a valid email address" : "Masukkan alamat e-mel yang sah",
        "Phone is required" : "Telefon diperlukan",
    },

    "ta" : {
        "Your password was too weak, we generated a new strong one" : "உங்கள் கடவுச்சொல் தீமையானது, நாம் புதிய வலுப்பான கடவுச்சொல் உருவாக்கி உள்ளோம்",
        "Please save it!" : "அதை சேமிக்கவும்!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "முதல் பெயர் 2 எழுத்துக்குக்காக உள்ளிடப்பட வேண்டும், குறைந்தது 2 எழுத்துக்கு, சிலந்த குறியீடுகள் அல்லது இடங்கள் இல்லை",
        "Last name must be more than 2 characters, no special symbols or spaces" : "கடைசி பெயர் 2 எழுத்துக்குக்காக உள்ளிடப்பட வேண்டும், குறைந்தது 2 எழுத்துக்கு, சிலந்த குறியீடுகள் அல்லது இடங்கள் இல்லை",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "கடவுச்சொல் 6 முதல் 12 எழுத்துக்குக்காக இருக்க வேண்டும், அதிகபடியாக எழுத்துக்கள் (A-Z, a-z) மற்றும் எண்கள் (0-9) அடைந்துள்ளன. சிலந்த குறியீடுகள் (^@()_#*+/\"?!=.}}~` மற்றும் இடங்கள் இல்லை",
        "Phone number must be between 7 and 11 characters long, no special characters" : "தொலைபேசி எண் 7 முதல் 11 எழுத்துக்குக்காக இருக்க வேண்டும், சிலந்த குறியீடுகள் இல்லை",
        "First name is required" : "முதல் பெயர் தேவை",
        "Can contain minimum 2 letters" : "குறைந்தது 2 எழுத்துக்கு உள்ளிடல் வேண்டும்",
        "Can contain maximum 25 letters" : "அதிகமாக 25 எழுத்துக்கு வரும்போது உள்ளிடல் வேண்டும்",
        "Last name is required" : "கடைசி பெயர் தேவை",
        "Password is required" : "கடவுச்சொல் தேவை",
        "Password must be at least 8 characters" : "குறைந்தது 8 எழுத்துக்கு வேண்டும்",
        "Password cannot exceed 12 characters" : "கடவுச்சொல் 12 எழுத்துக்கு விட கூடாது",
        "E-mail address is required" : "மின்னஞ்சல் முதல் தேவை",
        "Insert a valid email address" : "ஒரு செல்வாரின் செல்லுபடியாக இருக்க வேண்டும்",
        "Phone is required" : "தொலைபேசி முதல் தேவை",
    },

    "bs" : {
        "Your password was too weak, we generated a new strong one" : "Vaša lozinka bila je preslaba, generirali smo novu jaku.",
        "Please save it!" : "Molimo vas da je sačuvate!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Ime mora biti duže od 2 znaka, bez posebnih simbola ili razmaka.",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Prezime mora biti duže od 2 znaka, bez posebnih simbola ili razmaka.",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Lozinka mora imati između 6 i 12 znakova, uključujući slova (A-Z, a-z) i brojeve (0-9), bez posebnih simbola (^@()_#*+/\"?!=.}}~` i razmaka.",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Broj telefona mora imati između 7 i 11 znakova, bez posebnih znakova.",
        "First name is required" : "Ime je obavezno.",
        "Can contain minimum 2 letters" : "Može sadržavati minimalno 2 slova.",
        "Can contain maximum 25 letters" : "Može sadržavati maksimalno 25 slova.",
        "Last name is required" : "Prezime je obavezno.",
        "Password is required" : "Lozinka je obavezna.",
        "Password must be at least 8 characters" : "Lozinka mora imati barem 8 znakova.",
        "Password cannot exceed 12 characters" : "Lozinka ne smije biti duža od 12 znakova.",
        "E-mail address is required" : "E-mail adresa je obavezna.",
        "Insert a valid email address" : "Unesite ispravnu e-mail adresu.",
        "Phone is required" : "Telefon je obavezan.",
    },

    "th" : {
        "Your password was too weak, we generated a new strong one" : "รหัสผ่านของคุณอ่อนแอเกินไป เราได้สร้างรหัสผ่านใหม่ที่แข็งแรงขึ้นแล้ว",
        "Please save it!" : "โปรดบันทึกมัน!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "ชื่อจริงต้องมีมากกว่า 2 ตัวอักษร โดยไม่มีสัญลักษณ์พิเศษหรือช่องว่าง",
        "Last name must be more than 2 characters, no special symbols or spaces" : "นามสกุลต้องมีมากกว่า 2 ตัวอักษร โดยไม่มีสัญลักษณ์พิเศษหรือช่องว่าง",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "รหัสผ่านต้องมีความยาวระหว่าง 6 ถึง 12 ตัวอักษร รวมถึงตัวอักษร (A-Z, a-z) และตัวเลข (0-9) โดยไม่มีสัญลักษณ์พิเศษ (^@()_#*+/\"?!=.}}~` และช่องว่าง",
        "Phone number must be between 7 and 11 characters long, no special characters" : "หมายเลขโทรศัพท์ต้องมีความยาวระหว่าง 7 ถึง 11 ตัว โดยไม่มีสัญลักษณ์พิเศษ",
        "First name is required" : "ต้องกรอกชื่อจริง",
        "Can contain minimum 2 letters" : "สามารถมีตัวอักษรได้ต่ำสุด 2 ตัว",
        "Can contain maximum 25 letters" : "สามารถมีตัวอักษรได้สูงสุด 25 ตัว",
        "Last name is required" : "ต้องกรอกนามสกุล",
        "Password is required" : "ต้องกรอกรหัสผ่าน",
        "Password must be at least 8 characters" : "รหัสผ่านต้องมีอย่างน้อย 8 ตัว",
        "Password cannot exceed 12 characters" : "รหัสผ่านไม่สามารถเกิน 12 ตัวอักษรได้",
        "E-mail address is required" : "ต้องกรอกที่อยู่อีเมล",
        "Insert a valid email address" : "ใส่ที่อยู่อีเมลที่ถูกต้อง",
        "Phone is required" : "ต้องกรอกหมายเลขโทรศัพท์",
    },

    "ja" : {
        "Your password was too weak, we generated a new strong one" : "パスワードが弱すぎました、新しい強力なパスワードを生成しました。",
        "Please save it!" : "保存してください！",
        "First name must be longer than 2 characters, without special symbols or spaces" : "名前は2文字以上で、特殊記号や空白なしでなければなりません。",
        "Last name must be more than 2 characters, no special symbols or spaces" : "姓は2文字以上で、特殊記号や空白なしでなければなりません。",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "パスワードは6文字から12文字の間で、文字（A-Z、a-z）と数字（0-9）を含む必要があります。特殊記号（^@()_#*+/\"?!=.}}~`）や空白なしでなければなりません。",
        "Phone number must be between 7 and 11 characters long, no special characters" : "電話番号は7文字から11文字の間で、特殊文字なしでなければなりません。",
        "First name is required" : "名前は必須です。",
        "Can contain minimum 2 letters" : "最低2文字含むことができます。",
        "Can contain maximum 25 letters" : "最大25文字まで含むことができます。",
        "Last name is required" : "姓は必須です。",
        "Password is required" : "パスワードは必須です。",
        "Password must be at least 8 characters" : "パスワードは少なくとも8文字でなければなりません。",
        "Password cannot exceed 12 characters" : "パスワードは12文字を超えてはいけません。",
        "E-mail address is required" : "電子メールアドレスは必須です。",
        "Insert a valid email address" : "有効な電子メールアドレスを挿入してください。",
        "Phone is required" : "電話番号は必須です。",
    },

    "ko" : {
        "Your password was too weak, we generated a new strong one" : "비밀번호가 너무 약해서, 새로운 강력한 비밀번호를 생성했습니다.",
        "Please save it!" : "반드시 저장하세요!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "이름은 특수 기호나 공백 없이 2자 이상이어야 합니다.",
        "Last name must be more than 2 characters, no special symbols or spaces" : "성은 특수 기호나 공백 없이 2자 이상이어야 합니다.",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "비밀번호는 문자 (A-Z, a-z)와 숫자 (0-9)를 포함하여 6자에서 12자 사이여야 합니다. 특수 기호 (^@()_#*+/\"?!=.}}~` 및 공백 없이",
        "Phone number must be between 7 and 11 characters long, no special characters" : "전화번호는 특수 문자 없이 7자에서 11자 사이여야 합니다.",
        "First name is required" : "이름은 필수 항목입니다.",
        "Can contain minimum 2 letters" : "최소 2자 이상의 문자를 포함할 수 있습니다.",
        "Can contain maximum 25 letters" : "최대 25자의 문자를 포함할 수 있습니다.",
        "Last name is required" : "성은 필수 항목입니다.",
        "Password is required" : "비밀번호는 필수 항목입니다.",
        "Password must be at least 8 characters" : "비밀번호는 최소 8자 이어야 합니다.",
        "Password cannot exceed 12 characters" : "비밀번호는 12자를 초과할 수 없습니다.",
        "E-mail address is required" : "이메일 주소는 필수 항목입니다.",
        "Insert a valid email address" : "유효한 이메일 주소를 입력하세요.",
        "Phone is required" : "전화번호는 필수 항목입니다.",
    },

    "af" : {
        "Your password was too weak, we generated a new strong one" : "Jou wagwoord was te swak, ons het 'n nuwe sterk een gegenereer",
        "Please save it!" : "Stoor dit asseblief!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Eerste naam moet langer as 2 karakters wees, sonder spesiale tekens of spasies",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Laaste naam moet meer as 2 karakters wees, geen spesiale tekens of spasies",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Die wagwoord moet tussen 6 en 12 karakters wees, insluitend letters (A-Z, a-z) en syfers (0-9), sonder spesiale tekens (^@()_#*+/\"?!=.}}~` en spasies",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Telefoonnommer moet tussen 7 en 11 karakters lank wees, geen spesiale karakters nie.",
        "First name is required" : "Eerste naam is verpligtend",
        "Can contain minimum 2 letters" : "Dit kan minimum 2 letters bevat",
        "Can contain maximum 25 letters" : "Dit kan maksimum 25 letters bevat",
        "Last name is required" : "Laaste naam is verpligtend",
        "Password is required" : "Wagwoord is verpligtend",
        "Password must be at least 8 characters" : "Wagwoord moet minstens 8 karakters wees",
        "Password cannot exceed 12 characters" : "Wagwoord mag nie 12 karakters oorskry nie",
        "E-mail address is required" : "E-posadres is verpligtend",
        "Insert a valid email address" : "Voer 'n geldige e-posadres in",
        "Phone is required" : "Voer 'n geldige e-posadres in",
    },

    "ru" : {
        "Your password was too weak, we generated a new strong one" : "Ваш пароль слишком слабый, мы сгенерировали новый, надёжный",
        "Please save it!" : "Пожалуйста, сохраните его!",
        "First name must be longer than 2 characters, without special symbols or spaces" : "Имя должно быть длиннее 2 символов, без специальных символов или пробелов",
        "Last name must be more than 2 characters, no special symbols or spaces" : "Фамилия должна быть длиннее 2 символов, без специальных символов или пробелов",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces" : "Пароль должен содержать от 6 до 12 символов, включая буквы (A-Z, a-z) и цифры (0-9). Без специальных символов (^@()_#*+/\"?!=.}}~` и пробелов",
        "Phone number must be between 7 and 11 characters long, no special characters" : "Номер телефона должен быть от 7 до 11 символов, без специальных символов",
        "First name is required" : "Имя обязательно",
        "Can contain minimum 2 letters" : "Может содержать минимум 2 буквы",
        "Can contain maximum 25 letters" : "Может содержать максимум 25 букв",
        "Last name is required" : "Фамилия обязательна",
        "Password is required" : "Пароль обязателен",
        "Password must be at least 8 characters" : "Пароль должен содержать не менее 8 символов",
        "Password cannot exceed 12 characters" : "Пароль не должен превышать 12 символов",
        "E-mail address is required" : "Электронная почта обязательна",
        "Insert a valid email address" : "Введите действительный адрес электронной почты",
        "Phone is required" : "Телефон обязателен",
    },
    "mk": {
        "Your password was too weak, we generated a new strong one": "Вашата лозинка беше премногу слаба, генериравме нова силна лозинка",
        "Please save it!": "Ве молиме зачувајте ја!",
        "First name must be longer than 2 characters, without special symbols or spaces": "Името мора да биде подолго од 2 карактери, без специјални символи или празнини",
        "Last name must be more than 2 characters, no special symbols or spaces": "Презимето мора да биде подолго од 2 карактери, без специјални символи или празнини",
        "The password must be between 6 and 12 characters, including letters (A-Z, a-z) and numbers (0-9). Without special symbols (^@()_#*+/\"?!=.}}~` and spaces": "Лозинката мора да биде помеѓу 6 и 12 карактери, вклучувајќи букви (A-Z, a-z) и броеви (0-9). Без специјални символи (^@()_#*+/\"?!=.}}~` и празнини",
        "Phone number must be between 7 and 11 characters long, no special characters": "Бројот на телефон мора да биде помеѓу 7 и 11 карактери, без специјални символи",
        "First name is required": "Името е задолжително",
        "Can contain minimum 2 letters": "Може да содржи најмалку 2 букви",
        "Can contain maximum 25 letters": "Може да содржи најмногу 25 букви",
        "Last name is required": "Презимето е задолжително",
        "Password is required": "Лозинката е задолжителна",
        "Password must be at least 8 characters": "Лозинката мора да биде најмалку 8 карактери",
        "Password cannot exceed 12 characters": "Лозинката не смее да надминува 12 карактери",
        "E-mail address is required": "Е-адресата е задолжителна",
        "Insert a valid email address": "Вметнете валидна е-адреса",
        "Phone is required": "Телефонскиот број е задолжителен"
    }
};